<a href="https://colab.research.google.com/github/heena2248/APIs-usage-in-Python/blob/main/API_usage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.2.4-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.4/51.4 KB 1.3 MB/s eta 0:00:00
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (2022.7)
Collecting requests>=2.26
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 3.0 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from yfinance) (0.0.11)
Collecting cryptography>=3.3.2
  Downloading cryptography-39.0.0-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 32.7 MB/s eta 0:00:00
Collecting frozendict>=2.3.4
  Downloading frozendict-2.3.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 KB 8.0 MB/s eta 0:00:00
Collecting beautifulsoup4>=4.11.1
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 KB 10.4 MB/s eta 0:00:00
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 KB 4.8 MB/s eta 0:00:00
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.8/dist-packages (from yfinance) (4.9.2)
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (1.15.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)
Installing collected packages: soupsieve, requests, html5lib, frozendict, cryptography, beautifulsoup4, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: html5lib
    Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Successfully installed beautifulsoup4-4.11.1 cryptography-39.0.0 frozendict-2.3.4 html5lib-1.1 requests-2.28.2 soupsieve-2.3.2.post1 yfinance-0.2.4

In [ ]:
import yfinance as yf
ticker = yf.Ticker('GOOGL').info
market_price = ticker['regularMarketPrice']
previous_close_price = ticker['regularMarketPreviousClose']
print('Ticker: GOOGL')
print('Market Price:', market_price)
print('Previous Close Price:', previous_close_price)

Ticker: GOOGL
Market Price: 99.79
Previous Close Price: 98.02

In [ ]:
pip install geopy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: geopy in /usr/local/lib/python3.8/dist-packages (1.17.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /usr/local/lib/python3.8/dist-packages (from geopy) (1.52)

In [ ]:
# Import pandas package  
import pandas as pd 
import numpy as np
    
# Define a dictionary containing  data 
data = {'City':['Bangalore', 'Mumbai', 'Chennai', 'Delhi']} 
    
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data) 
    
# Observe the result 
df

        City
0  Bangalore
1     Mumbai
2    Chennai
3      Delhi

In [ ]:
from geopy.exc import GeocoderTimedOut
from geopy.geocoders import Nominatim
   
# declare an empty list to store
# latitude and longitude of values 
# of city column
longitude = []
latitude = []
   
# function to find the coordinate
# of a given city 
def findGeocode(city):
       
    # try and catch is used to overcome
    # the exception thrown by geolocator
    # using geocodertimedout  
    try:
          
        # Specify the user_agent as your
        # app name it should not be none
        geolocator = Nominatim(user_agent="Weather_app")
          
        return geolocator.geocode(city)
      
    except GeocoderTimedOut:
          
        return findGeocode(city)    
  
# each value from city column
# will be fetched and sent to
# function find_geocode   
for i in (df["City"]):
      
    if findGeocode(i) != None:
           
        loc = findGeocode(i)
          
        # coordinates returned from 
        # function is stored into
        # two separate list
        latitude.append(loc.latitude)
        longitude.append(loc.longitude)
       
    # if coordinate for a city not
    # found, insert "NaN" indicating 
    # missing value 
    else:
        latitude.append(np.nan)
        longitude.append(np.nan)

In [ ]:
df["Longitude"] = longitude
df["Latitude"] = latitude
  
df

        City  Longitude   Latitude
0  Bangalore  77.590082  12.976794
1     Mumbai  72.878176  19.078545
2    Chennai  80.270186  13.083694
3      Delhi  77.221939  28.651718

In [ ]:
import yfinance as yf
start_date = '2023-01-01'
end_date = '2023-01-23'
# Add multiple space separated tickers here
ticker = 'GOOGL MSFT TSLA'
data = yf.download(ticker, start_date, end_date)
print(data.tail())

[*********************100%***********************]  3 of 3 completed
                           Adj Close                              Close  \
                               GOOGL        MSFT        TSLA      GOOGL
Date
2023-01-13 00:00:00-05:00  92.120003  239.229996  122.400002  92.120003
2023-01-17 00:00:00-05:00  91.290001  240.350006  131.490005  91.290001
2023-01-18 00:00:00-05:00  91.120003  235.809998  128.779999  91.120003
2023-01-19 00:00:00-05:00  93.050003  231.929993  127.169998  93.050003
2023-01-20 00:00:00-05:00  98.019997  240.220001  133.419998  98.019997

                                                        High              \
                                 MSFT        TSLA      GOOGL        MSFT
Date
2023-01-13 00:00:00-05:00  239.229996  122.400002  92.190002  239.369995
2023-01-17 00:00:00-05:00  240.350006  131.490005  92.250000  240.910004
2023-01-18 00:00:00-05:00  235.809998  128.779999  92.800003  242.380005
2023-01-19 00:00:00-05:00  231.929993  127.169998  93.610001  235.520004
2023-01-20 00:00:00-05:00  240.220001  133.419998  98.300003  240.740005

                                             Low                          \
                                 TSLA      GOOGL        MSFT        TSLA
Date
2023-01-13 00:00:00-05:00  122.629997  90.129997  234.919998  115.599998
2023-01-17 00:00:00-05:00  131.699997  90.050003  237.089996  125.019997
2023-01-18 00:00:00-05:00  136.679993  90.639999  235.520004  127.010002
2023-01-19 00:00:00-05:00  129.990005  90.629997  230.679993  124.309998
2023-01-20 00:00:00-05:00  133.509995  95.019997  234.509995  127.349998

                                Open                            Volume  \
                               GOOGL        MSFT        TSLA     GOOGL
Date
2023-01-13 00:00:00-05:00  90.849998  237.000000  116.550003  26309900
2023-01-17 00:00:00-05:00  92.059998  237.970001  125.699997  32602400
2023-01-18 00:00:00-05:00  92.139999  241.570007  136.559998  29116700
2023-01-19 00:00:00-05:00  90.720001  233.779999  127.260002  37000400
2023-01-20 00:00:00-05:00  95.099998  234.860001  128.679993  63037300


                               MSFT       TSLA
Date
2023-01-13 00:00:00-05:00  21317700  180439300
2023-01-17 00:00:00-05:00  29831300  186477000
2023-01-18 00:00:00-05:00  30028700  195680300
2023-01-19 00:00:00-05:00  28623000  170291900
2023-01-20 00:00:00-05:00  35323400  138429900